Repository wecode-bootcamp-korea/10-DrMozart-frontend, pull requests merged in 2020-07, with the labels that each got.

#3 Add: Dr.jart Config.js 추가, 불필요코드 제거
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.js
  src/Components/Nav/SideNav/SideNav.scss
  src/Config.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainStory/MainStory.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#4 Modify: Dr.jart Main CSS 코드 재수정
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.scss
  src/Pages/Main/Main.scss
Labels: Status: 리뷰 요청

#5 Refactor: Dr.Jart [김정호] Login Layout 및 일부 기능구현
  package-lock.json
  public/images/Dr.Mozart+.html
  public/images/Dr.Mozart+_files/1.chunk.js.다운로드
  public/images/Dr.Mozart+_files/bundle.js.다운로드
  public/images/Dr.Mozart+_files/main.7df23f7e2917cf2dfd8b.hot-update.js.다운로드
  public/images/Dr.Mozart+_files/main.chunk.js.다운로드
  public/images/Login2.png
  public/images/checkbox.png
  public/images/checkbox2.png
  public/images/checkbox3.gif
  public/images/checkbox3.webp
  public/images/drjartlogo.png
  public/images/facebooklogo.jpg
  public/images/facebooklogo2.png
  public/images/facebooklogo4.png
  public/images/facebooklogoreal.png
  public/images/fafa.png
  public/images/icon_loginJoin.gif
  public/images/inp_check.webp
  public/images/kaka.png
  public/images/kakaokakao.jpg
  public/images/kakaotalklogin.png
  public/images/kakaotalklogo.jfif
  public/images/kakaotalkreal.jpg
  public/images/kakaotalksns.png
  public/images/ktkt.jpg
  public/images/line.png
  public/images/login.png
  public/images/mark.png
  public/images/naverlogo.png
  public/images/naverreal.jpg
  public/images/naversns.png
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/member/member3.js
  src/Pages/member/member3.scss
  src/Routes.js
Labels: Status: 수정 요청

#8 Refactor: 메인페이지 리뷰내용 반영
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.js
  src/Components/Nav/SideNav/SideNav.scss
  src/Config.js
  src/Pages/Main/BestProduct/BestProduct.js
  src/Pages/Main/BestProduct/BestProduct.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainStory/MainStory.js
  src/Pages/Main/MainStory/MainStory.scss
  src/Pages/Main/OnlineProduct/OnlineProduct.js
  src/Pages/Main/OnlineProduct/OnlineProduct.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Main/Review/Review.scss
  src/Pages/Products/Product/Each.js
  src/Pages/Products/Product/Product.js
  src/Pages/Products/Product/Product.scss
Labels: Status: 리뷰 요청

#6 Refactor: [Dr.Jart] 불필요 코드 삭제 및 수정
  public/images/detail01.png
  public/images/detail02.png
  public/images/detail03.png
  public/images/detail04.png
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Products/Product/Each.js
  src/Pages/Products/Product/Product.js
  src/Routes.js
Labels: Status: 수정 요청

#7 Add: 제품 상세페이지 네비게이션 추가
  public/images/ico_cart_white.png
  public/images/ico_heart_white.png
  src/Components/Nav/Nav.js
  src/Components/Nav/SideNav/SideNav.js
  src/Components/Nav/SideNav/SideNav.scss
  src/Config.js
  src/Pages/Detail/DetailNav.js
  src/Pages/Detail/DetailNav.scss
  src/Pages/Detail/FloatingNav.js
  src/Pages/Detail/FloatingNav.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainStory/MainStory.js
  src/Pages/Main/MainStory/MainStory.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Main/Review/Review.scss
  src/Pages/Products/Product/Each.js
  src/Pages/Products/Product/Product.js
  src/Pages/Products/Product/Product.scss
  src/Routes.js
  src/Util/throttle.js
Labels: Status: 수정 요청

#9 Refactor: [권한성] Dr.Jart 메인 리팩토링
  src/Pages/Products/Product/Each.js
  src/Pages/Products/Product/Product.js
Labels: Status: 리뷰 요청

#11 Fix: 오류 해결
  public/images/login.png
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.scss
  src/Config.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailNav.js
  src/Pages/Detail/FloatingNav.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainStory/MainStory.js
  src/Pages/Main/MainStory/MainStory.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Main/Review/Review.scss
  src/Pages/Products/Product/Each.js
  src/Routes.js
Labels: Status: 리뷰 요청

#12 Add: 로그인 페이지 레이아웃 및 기능 완성
  debug.log
  package-lock.json
  package.json
  public/images/Dr.Mozart+.html
  public/images/Dr.Mozart+_files/1.chunk.js.다운로드
  public/images/Dr.Mozart+_files/bundle.js.다운로드
  public/images/Dr.Mozart+_files/main.7df23f7e2917cf2dfd8b.hot-update.js.다운로드
  public/images/Dr.Mozart+_files/main.chunk.js.다운로드
  public/images/Login2.png
  public/images/checkbox.png
  public/images/checkbox3.webp
  public/images/facebooklogo.jpg
  public/images/facebooklogo2.png
  public/images/facebooklogo4.png
  public/images/facebooklogoreal.png
  public/images/fafa.png
  public/images/ico_loginSns.png
  public/images/inp_check.webp
  public/images/kaka.png
  public/images/kakaokakao.jpg
  public/images/kakaotalklogin.png
  public/images/kakaotalklogo.jfif
  public/images/kakaotalkreal.jpg
  public/images/kakaotalksns.png
  public/images/ktkt.jpg
  public/images/line.png
  public/images/naverlogo.png
  public/images/naverreal.jpg
  public/images/naversns.png
  public/index.html
  src/Components/Nav/SideNav/SideNav.js
  src/Config.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignIn/SignIn.js
  src/Pages/SignIn/SignIn.scss
  src/Pages/member/member3.js
  src/Pages/member/member3.scss
  src/Routes.js
Labels: Status: Accepted

#16 Refactor: Dr.Jart Detail 코드 리팩토링
  src/Pages/Detail/Detail.scss
Labels: Status: 리뷰 요청

#14 Refactor: SingUp Page 리뷰내용 반영
  public/images/signup.gif
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
Labels: Status: Accepted

#15 Refactor: Dr.Jart Main 코드 리팩토링
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Routes.js
Labels: Status: Accepted

#17 Refactor: CartList 페이지 리뷰적용 완료
  public/images/delBtn.png
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
Labels: Status: 리뷰 요청

#18 Refactor: Main 페이지 Transition 추가 및 코드일부 수정
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SideNav/SideNav.js
  src/Components/Nav/SideNav/SideNav.scss
  src/Config.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainStory/MainStory.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Main/Review/Review.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#20 Add: 장바구니 기능구현 완료
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Cartlist.js
  src/Pages/Cart/Cartlist.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Products/Product/Each.js
  src/Pages/SignIn/SignIn.js
Labels: Status: Accepted

#21 README.md
  README.md
Labels: Status: Accepted

#23 Fix: API 주소 수정
  src/Components/Nav/Nav.js
  src/Config.js
  src/Pages/Products/Product/Product.js
Labels: Status: 리뷰 요청
